name: Github Actions Deploy
on: [push]
jobs:
  CDK-Deploy-Frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3

      - name: Install dependencies for the react app
        working-directory: ./src/testing-react-app
        run: npm install

      - name: Build React App
        working-directory: ./src/testing-react-app
        run: npm run build
      
      - name: Deploy CDK stacks to AWS account
        working-directory: ./
        run: |
          npm install
          cdk deploy --all --require-approval=never
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      
